force-app/main/default/objects/Leave_Application__c/Leave_Application__c.object-meta.xml
<CustomObject>
    <description>Object for storing leave applications submitted by an employee</description>
    <label>Leave Application</label>
    <nameField>
        <displayFormat>LA-{0000}</displayFormat>
        <label>Leave Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Leave_Application__c/fields/Current_Leave_Balance__c.field-meta.xml
<CustomField>
    <fullName>Current_Leave_Balance__c</fullName>
    <description>Current Leave Balance</description>
    <formula>Employee_Name__r.Current_Leave_Balance__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Current Leave Balance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Leave_Application__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of Leave</description>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Leave_Application__c/fields/Employee_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of employee</description>
    <label>Employee Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leave_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Leave_Application__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Leave End Date</description>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Leave_Application__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Lease start date</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Leave_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Draft&quot;</defaultValue>
    <description>Status of the leave application</description>
    <inlineHelpText>This fields shows the current status of the application for leave.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leave_Application__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of leave that the employee wants to take</description>
    <label>Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LeaveApplicationController.cls
public with sharing class LeaveApplicationController {
    /**
     * Retrieves the current user's leave requests from the Leave_Request__c object.
     * @return A list of Leave_Request__c records for the current user.
     */
    @AuraEnabled(cacheable=true)
    public static List<Leave_Application__c> getMyLeaves() {
        try {
            // Query to fetch leave requests for the current user
            List<Leave_Application__c> leaveApplications = [
                SELECT
                    Id,
                    Name,
                    Start_Date__c,
                    End_Date__c,
                    Type__c,
                    Description__c,
                    Number_of_Days__c,
                    Manager_Comments__c,Current_Leave_Balance__c,
                    Status__c
                FROM Leave_Application__c
                WHERE Employee_Name__c = :UserInfo.getUserId()
                ORDER BY CreatedDate DESC];

            return leaveApplications;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    /**
     * Retrieves leave requests for the subordinates of the current user.
     * @return A list of Leave_Request__c records for the current user's subordinates.
     */
    @AuraEnabled(cacheable=true)
    public static List<Leave_Application__c> getLeaveRequests() {
        try {
            // Query to fetch leave requests for subordinates of the current user
            List<Leave_Application__c> leaveApplications = [
                SELECT
                    Id,
                    Name,
                    Start_Date__c,
                    End_Date__c,
                    Type__c,
                    Description__c,
                    Manager_Comments__c,
                    Status__c,
                    Number_of_Days__c,Current_Leave_Balance__c,
                    Employee_Name__r.ManagerId,
                    Employee_Name__r.Name
                FROM Leave_Application__c
                WHERE Employee_Name__r.ManagerId = :UserInfo.getUserId()
                ORDER BY CreatedDate DESC];
            return leaveApplications;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    /**
     * Retrieve the Picklist Values for the Leave Type field
     */
    @AuraEnabled(cacheable=true)
    public static List<String> getLeaveTypeValues() {
        List<String> leaveTypeList = new List<String>();
        
        // Fetch values from custom metadata
        List<Leave_Types__mdt> leaveTypes = [SELECT LeaveType__c FROM Leave_Types__mdt];

        for (Leave_Types__mdt lt : leaveTypes) {
            leaveTypeList.add(lt.LeaveType__c);
        }
        
        return leaveTypeList;
    }

    @AuraEnabled(cacheable=true)
    public static Boolean checkIfUserisManager(Id recordId) {
        Boolean userIsManager = false;

        List<User> userDetails = [SELECT Id, ManagerId FROM User where ManagerId=:recordId];
        System.debug('User' + userDetails);
        if(!userDetails.isEmpty() ){
            userIsManager = true;
        }else{
            userIsManager = false;
        }
        return userIsManager;
    }

    /**
     * Retrieves and calculates the current user's leave balance.
     * @return An instance of LeaveBalance with calculated leave hours.
     */
    @AuraEnabled(cacheable=true)
    public static LeaveBalanceWrapperClass getLeaveBalance() {
        LeaveBalanceWrapperClass leaveBalance = new LeaveBalanceWrapperClass();
        try {
            List<User> userInfo = [ SELECT Id, Name, Email, Current_Leave_Balance__c, Leave_Days_To_Be_Approved__c, ManagerId
                                FROM User
                                WHERE Id = :UserInfo.getUserId()
                                ORDER BY CreatedDate DESC];
            for (User user : userInfo) {
                leaveBalance.currentBalance = user.Current_Leave_Balance__c;
                leaveBalance.balanceToBeApproved = user.Leave_Days_To_Be_Approved__c;
            }
        return leaveBalance;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    /**
     * Method to calculate the total number of weekdays between two dates.
     * @param startDate The start date of the period.
     * @param endDate The end date of the period.
     * @return The total number of weekdays in the given date range.
     */
    @AuraEnabled(cacheable=true)
    public static Integer getTotalLeaveDays(Date startDate, Date endDate) {
        Date start = startDate;
        Date endDateCalc = endDate;
        
        Integer totalDays = 0;
        BusinessHours workingHours = [SELECT Id FROM BusinessHours WHERE IsDefault = true limit 1];
        System.debug(workingHours);

        System.debug('startDate' + startDate);
        System.debug('workingHours' + workingHours);
        System.debug('endDateCalc' + endDateCalc);

            // Add 1 day to include the end date in the calculation
            while(start <= endDateCalc){

                System.debug('in while');
                if(BusinessHours.isWithin(workingHours.Id, start)){
                    totalDays++;
                }
                start = start.addDays(1);
        }

        return totalDays;
    }


    @AuraEnabled
    public static String approveRejectRequest(String recordId, Boolean isApproved, String managerComments){
        try{
            String resultString = isApproved ? 'Approved': 'Rejected';
           
            Leave_Application__c leaveRequest = [Select Employee_Name__c, Status__c , Manager_Comments__c from Leave_Application__c where id=:recordId];
            User userDetails = [SELECT ManagerID FROM User where id=:leaveRequest.Employee_Name__c];
            //check if current user is manager of requester.
            Boolean isCurrentUserManagerOfRecordOwner  = (userDetails.ManagerID == UserInfo.getUserId() )? true:false;
            
            if(isCurrentUserManagerOfRecordOwner){
                if(leaveRequest != null){
                    if(isApproved){
                        leaveRequest.Status__c = 'Approved';
                        leaveRequest.Manager_Comments__c = managerComments;
                    } else{
                    //to reject use 'Reject'
                        leaveRequest.Status__c = 'Not Approved';
                        leaveRequest.Manager_Comments__c = managerComments;
                    }
                }  
                Database.SaveResult saveResult = Database.update(leaveRequest);
                if (!saveResult.isSuccess()) { 
                    return resultString;
                }
                return resultString;
            }
            else{
                return 'Only the Manager can Approve/Reject leves';
            }
        }
        catch(Exception e){ throw new AuraHandledException(e.getMessage()); }
    }



    /**
     * Wrapper class to handle leave balance calculation.
     */
    public class LeaveBalanceWrapperClass {
        @AuraEnabled
        public Decimal currentBalance { get; set; }
        @AuraEnabled
        public Decimal balanceToBeApproved { get; set; }
    }
}